default_language_version:
    python: python3
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: 'v0.6.5'
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]
          - id: ruff-format
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: end-of-file-fixer # Ensures newline at end of files
          - id: trailing-whitespace # Removes trailing spaces
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            types_or: [css, scss, json, yaml]
            additional_dependencies:
                # Keep in sync with package.json
                - prettier@3.1.0
    - repo: https://github.com/rtts/djhtml
      rev: 3.0.6
      hooks:
          - id: djhtml
